config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users, controllers: { :sessions => "users/sessions", :registrations => 'users/registrations', 
    :confirmations => 'users/confirmations', :passwords => "users/passwords" }
 
  resources :users
  resources :appointments
  get "/courses/catalogo"=> "courses#catalogo"
  get "/courses/mis_materias"=> "courses#mis_materias"
  resources :courses
  get "/courses/:id/cuestionario/"=>"courses#cuestionario"
  get "/courses/:id/guardar_resultados"=>"courses#guardar_resultados"
  get "/courses/:id/guardar_comentario"=>"courses#guardar_comentario"
  
  resources :sections
  get "/courses/:id/agregar_seccion/"=>"courses#agregar_seccion"
  get "/appointments/:id/confirmar_cita/"=> "appointments#confirmar_cita"
  post "/appointments/generar_reporte/"=> "appointments#generar_reporte"
  resources :schedules
  get 'administracion/index'
  get "consejeria/index"
  root :to => "consejeria#index"
  get "consejeria/" => "consejeria#index"
  
  
  

end

app/models/schedule.rb
# == Schema Information
#
# Table name: schedules
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  dia_semana  :string(255)
#  hora_inicio :time
#  hora_fin    :time
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

# Clase que modela los horarios de atención de los consejeros en objetos de tipo Schedule
class Schedule < ActiveRecord::Base
  belongs_to :consejero, :class_name => 'User',:foreign_key=>'user_id'
  require 'tod'
  serialize :time, Tod::TimeOfDay
  @dias =['lunes','martes,','miercoles','jueves','viernes']
end

app/controllers/schedules_controller.rb
# Clase encargada de controlar las acciones de objetos de tipo Schedule entre la base de datos y la vista 
class SchedulesController < ApplicationController
  
  #Define los parámetros que son alterables por el controlador
  def schedule_params
    params.require(:schedule).permit(:id,:user_id,:dia_semana, :hora_inicio, :hora_fin)
  end
  
  # Método que accede a los registros de de tipo Schedule del consejero
  # * *Resultado* :
  #   - Lista de objetos de tipo Schedule almacenado en la variable @horarios
  def index
    @horarios= Schedule.where :user_id => current_user.id
  end


  # CU016-R02
  # Método que prepara el objeto de tipo Schedule para crearlo
  # * *Resultado* :
  #   - Asigna a un objeto de tipo Schedule vacío a la variable @horario
  def new
    @dias =['lunes','martes','miercoles','jueves','viernes']
    @horario=Schedule.new
  end

  # CU016-R02
  # Método que agrega un objeto de tipo Schedule a la base de datos
  # * *Parámetros* :
  #   - +user_params+ -> hash con la información del objeto de tipo Schedule
  # * *Resultado* :
  #   - Un nuevo horario de tipo Schedule se guarda como registro en la base de datos
  def create
    @horario = Schedule.new(schedule_params)
    @horario.user_id=current_user.id
    puts "PARAMETROS------------------"
    puts params
    @horario.hora_fin = @horario.hora_inicio + 3600
    
    if @horario.save
      redirect_to :schedules, :flash => { :success => 'Horario de atención creado exitosamente.' }
    else
      render :action => 'index'
    end
  end

  def update
  end
  
  # Método que elimina un registro de tipo Schedule
  # * *Parámetros*    :
  #   - +id+ -> identificador único del registro de tipo Schedule
  # * *Resultado* :
  #   - El horario se elimina exitosamente
  def destroy
    @user = Schedule.find(params[:id])
    @user.destroy
    redirect_to schedules_path, :flash => { :success => 'Horario eliminado correctamente.' }
  end
end

app/helpers/schedules_helper.rb
# Módulo de métodos de ayuda específicos para las vistas concernientes a Schedule. Es un clase vacía pues no ha habido necesidad hasta el momento ningun método
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_for @horario, url: schedules_path, html:{class:'form-horizontal',:method =>:post} do |f| %>
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal">
		&times;
	</button>
	<h3>Nuevo Horario</h3>
</div>
<div class="modal-body">

	<div class="form-group">
		<div class="col-sm-2">
			<%= f.label :dia_semana,class:"control-label"%>
		</div>
		<div class="col-sm-9">
			<%= f.select(:dia_semana,@dias.map{|val| [val.capitalize,val.capitalize]},{},{class:"form-control"})%>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-2">
			<%= f.label :hora_inicio,class:"control-label"%>
		</div>
		<div class="col-sm-9">
			<div class="input-group input-append bootstrap-timepicker" id="horaInicio">
				<%= f.time_field(:hora_inicio ,class:"form-control time-picker")%>
				<span class="input-group-addon"> <i class="fa fa-clock-o"></i> </span>
			</div>
		</div>
	</div>
</div>
<div class="modal-footer">
	<div class="actions">
		<div class="actions">
			<button class="btn btn-green" type="submit">
				Guardar
			</button>
		</div>
	</div>
</div>
<% end %>


app/views/schedules/create.html.erb
<h1>Schedules#create</h1>
<p>Find me in app/views/schedules/create.html.erb</p>

app/views/schedules/destroy.html.erb
<h1>Schedules#destroy</h1>
<p>Find me in app/views/schedules/destroy.html.erb</p>

app/views/schedules/index.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<i class="fa fa-external-link-square"></i>
				Horarios
				<div class="panel-tools"></div>
			</div>
			<div class="panel-body">
				<table class="table table-hover" id="sample-table-1">
					<thead>
						<tr>
							<th class="left">Día</th>
							<th class="left">Hora inicio</th>
							<th class="left">Hora fin</th>
							<th></th>
					</thead>
					<tbody>
						<%@horarios.each do |h|%>
						<tr>
							<td class="left"><%= h.dia_semana%></td>
							<td class="left"><%= h.hora_inicio.strftime('%I:%M %p')%></td>
							<td class="left"><%= h.hora_fin.strftime('%I:%M %p')%></td>
							<td class="left">
							<div class="visible-md visible-lg hidden-sm hidden-xs">
								<%= link_to schedule_path(h),class: "btn btn-xs btn-bricky tooltips",:data=>{:method=>"delete", :placement=>"top","original-title"=>"Eliminar"} do%>
								<i class="fa fa-times fa fa-white"></i>
								<%end%>
							</div>
							<div class="visible-xs visible-sm hidden-md hidden-lg">
								<div class="btn-group">
									<a class="btn btn-primary dropdown-toggle btn-sm" data-toggle="dropdown" href="#"> <i class="fa fa-cog"></i> <span class="caret"></span> </a>
									<ul role="menu" class="dropdown-menu pull-right">
										<li role="presentation">
											<%= link_to schedule_path(h),role: "menuitem",tabindex: "-1",:data=>{:method=>"delete", :placement=>"top","original-title"=>"Eliminar"} do%>
											<i class="fa fa-times"></i> Eliminar
											<%end%>
										</li>
									</ul>
								</div>
							</div>
							</td>
						</tr>
						<%end%>
					</tbody>
				</table>
				<%= link_to 'Agregar nuevo horario de atención',new_schedule_path, class: 'btn btn-blue btn-block',:remote => 'true'%>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="horario" tabindex="-1" data-width="760" style="display: none;"></div>


<!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->

app/views/schedules/new.html.erb
<h1>Schedules#new</h1>
<p>Find me in app/views/schedules/new.html.erb</p>

app/views/schedules/new.js.erb
$("#horario").html("<%= escape_javascript(render(:partial => "form"))%>");
$('#horario').modal('show');

app/views/schedules/show.html.erb
<h1>Schedules#show</h1>
<p>Find me in app/views/schedules/show.html.erb</p>

app/views/schedules/update.html.erb
<h1>Schedules#update</h1>
<p>Find me in app/views/schedules/update.html.erb</p>