config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users, controllers: { :sessions => "users/sessions", :registrations => 'users/registrations', 
    :confirmations => 'users/confirmations', :passwords => "users/passwords" }
 
  resources :users
  resources :appointments
  get "/courses/catalogo"=> "courses#catalogo"
  get "/courses/mis_materias"=> "courses#mis_materias"
  resources :courses
  get "/courses/:id/cuestionario/"=>"courses#cuestionario"
  get "/courses/:id/guardar_resultados"=>"courses#guardar_resultados"
  get "/courses/:id/guardar_comentario"=>"courses#guardar_comentario"
  
  resources :sections
  get "/courses/:id/agregar_seccion/"=>"courses#agregar_seccion"
  get "/appointments/:id/confirmar_cita/"=> "appointments#confirmar_cita"
  post "/appointments/generar_reporte/"=> "appointments#generar_reporte"
  resources :schedules
  get 'administracion/index'
  get "consejeria/index"
  root :to => "consejeria#index"
  get "consejeria/" => "consejeria#index"
  
  
  

end

app/controllers/courses_controller.rb
# Clase encargada de controlar las acciones concernientes a los objetos de tipo Course
class CoursesController < ApplicationController

  # Definicion de objeto actual de tipo course
  # * *Parámetros*    :
  #   - +id+ -> Identificador único del registro de tipo Course
  def set_course
    @materia=Course.find(params[:id])
  end
  
  # Parámetros permitidos para alterar provenientes de la vista
  def course_params
    params.require(:course).permit(:id,:nombre,:creditos, :descripcion,:intensidad,:dificultad,:utilidad,:numero_encuestas,:users_ids=>[] ,sections_attributes: [:id,:course_id,:semestre,:estado], comments_attributes: [:id,:comment_id,:user_id,:comment])
  end

  # Muestra un listado de los objetos de tipo Course para el usuario de tipo administrador.
  def index
    @materias= Course.all
  end
  
  # Muestra un listado de los objetos de tipo Course para cualquier tipo de usuario.
  def catalogo
    @materias= Course.all.order(:nombre)
  end
  
  # Muestra un listado de los objetos de tipo Course que el usuario ha evaluado y aprobado
  def mis_materias
    @vistas= current_user.courses
    @total_creditos= Course.sum(:creditos)
    @creditos_vistos=0
  end
  
  # Agrega un un objeto de tipo Comment y lo asocia a la materia actual
  # * *Parámetros*    :
  #   - +id+ -> Identificador único del registro de tipo Course
  def guardar_comentario
    set_course
    comment= Comment.new
    comment.comentario = params[:comment]
    comment.user=current_user
    @materia.comments<<comment
    if @materia.save
      redirect_to courses_path, :flash => { :success => 'Comentario agregado' }
    else
      redirect_to courses_path, :flash => { :error => 'No ha sido posible guardar el comentario.' }
    end
  end
  
  # Muestra los detalles de una materia
  # * *Parámetros*    :
  #   - +id+ -> Identificador único del registro de tipo Course
  def show
    @materia= Course.find(params[:id])
  end

  # Prepara un objeto de tipo Course para ser llenado a traves del formulario de la vista asociada
  def new
    @materia= Course.new
    @materia.sections.build
    @materia.comments.build
  end

  # Guarda la información del Objeto de tipo Course en la base de datos
  def create
    @materia = Course.new(course_params)
    @materia.numero_encuestas=0
    @materia.intensidad=0.0
    @materia.dificultad=0.0
    @materia.utilidad=0.0
    if @materia.save
      redirect_to :courses, :flash => { :success => 'Materia creada exitosamente.' }
    else
      render :action => 'index'
    end
  end
  
  # Accede y prepara el objeto de tipo Course para su edición en su vista asociada
  # * *Parámetros*    :
  #   - +id+ -> Identificador único del registro de tipo Course
  def edit
    @materia=Course.find(params[:id])
    @materia.sections.build
    @materia.comments.build
  end
  
  # Actualiza los datos del objeto de tipo Course y los modifica en la base de datos
  # * *Parámetros*    :
  #   - +id+ -> Identificador único del registro de tipo Course
  def update
    puts "PARAMETROS DE ACTUALIZACION DE CURSO"
    puts params
    
    @materia=Course.find(params[:id])
    if @materia.update_attributes(course_params)
      redirect_to course_url(@materia), success: 'Datos de materia actualizados satisfactoriamente.'
      #redirect_to :courses, :flash => { :success => 'Datos de materia actualizados satisfactoriamente.' }
    else
      redirect_to :courses, :flash => { :error => 'No ha sido posible actualizar los datos de la materia.' }
    end
  end
  
  # Agrega un objeto de tipo Section a la base de datos y los asocia a la materia actual
  # * *Parámetros*    :
  #   - +id+ -> Identificador único del registro de tipo Course
  def agregar_seccion
    @materia= Course.find(params[:id])
    @seccion=@materia.sections.build
  end
  
  # Accede a la informacion del Objeto de tipo Course actual y lo prepara para un formulario en la vista asociada
  def cuestionario
    puts "PARAMETROS DE CUESTIONARIO"
    puts params
    @materia= Course.find(params[:id])
  end
  
  # Guarda la información del formulario de cuestioario actualizando la información del objeto detipo Course en la  base de datos
  # * *Parámetros*    :
  #   - +id+ -> Identificador único del registro de tipo Course
  def guardar_resultados
    @materia= Course.find(params[:id])
    puts "PARAMETROS DE EVUALUACION"
    puts params
    @materia.dif_sum += params[:dificultad].to_i
    @materia.inten_sum += params[:intensidad].to_i
    @materia.util_sum += params[:utilidad].to_i
    @materia.numero_encuestas = @materia.numero_encuestas+1
    @materia.dificultad= @materia.dif_sum/@materia.numero_encuestas
    @materia.intensidad= @materia.inten_sum/@materia.numero_encuestas
    @materia.utilidad= @materia.util_sum/@materia.numero_encuestas
    @materia.users<<current_user
    if @materia.save
      redirect_to :courses, :flash => { :success => 'Materia evaluada correctamente.' }
    else
      redirect_to :courses, :flash => { :error => 'No ha sido posible guardar los datos de la materia.' }
    end
    
  end
  
  # Elimina un Objeto de tipo Course de la base de datos
  # * *Parámetros*    :
  #   - +id+ -> Identificador único del registro de tipo Course a eliminar
  def destroy
    @materia = Course.find(params[:id])
    if @materia.destroy
      redirect_to :courses, :flash => { :success => "Materia eliminada exitosamente."}
    else
      redirect_to :courses, :flash => { :error => "No se encontró la materia a eliminar"}
    end
  end
end

app/views/courses/_form.html.erb
<%= form_for @materia, url: courses_path, html:{class:'form-horizontal',:method =>:post} do |f| %>
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal">
		&times;
	</button>
	<h3>Nueva materia</h3>
</div>
<div class="modal-body">

	<div class="form-group">
		<div class="col-sm-2">
			<%= f.label :nombre,class:"control-label"%>
		</div>
		<div class="col-sm-9">
			<%= f.text_field(:nombre,{class:"form-control"})%>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-2">
			<%= f.label :creditos,class:"control-label"%>
		</div>
		<div class="col-sm-9">
			<%= f.text_field(:creditos ,class:"form-control")%>	
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-2">
			<%= f.label :descripcion,class:"control-label"%>
		</div>
		<div class="col-sm-9">
			<%= f.text_area(:descripcion ,class:"form-control")%>	
		</div>
	</div>
</div>
<div class="modal-footer">
	<div class="actions">
		<div class="actions">
			<button class="btn btn-green" type="submit">
				Guardar
			</button>
		</div>
	</div>
</div>
<% end %>


app/views/courses/_form_agregar_seccion.html.erb
<%= form_for @materia,url: course_path, html:{class:'form-horizontal'} do |f| %>

<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal">
		&times;
	</button>
	<h3>Nueva sección</h3>
</div>
<%=f.fields_for :sections do |sec|%>
<div class="modal-body">
	<div class="form-group">
		<div class="col-sm-2">
			<%= sec.label :semestre,class:"control-label"%>
		</div>
		<div class="col-sm-9">
			<%= sec.text_field(:semestre,{class:"form-control"})%>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-2">
			<%= sec.label :estado,class:"control-label"%>
		</div>
		<div class="col-sm-9">
			<%= sec.text_field(:estado ,class:"form-control")%>	
		</div>
	</div>
</div>
<%end%>
<div class="modal-footer">
	<div class="actions">
		<div class="actions">
			<button class="btn btn-green" type="submit">
				Guardar
			</button>
		</div>
	</div>
</div>

<% end %>

app/views/courses/_form_cuestionario.html.erb
<%= form_tag(@materia.id.to_s+"/guardar_resultados",:method=>"get") do%>
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal">
		&times;
	</button>
	<h3>Evaluación de materia: <%=@materia.nombre%></h3>
</div>
<div class="modal-body">
	<div class="well well-sm">
	<h4>Considera ud que los temas tratados en clase son dificiles de asimilar o entender?</h4>
	<%(1..5).each do |i|%>
		<%= label_tag(:dificultad,class: 'radio-inline') do%>
				<%= radio_button_tag(:dificultad,i.to_s ,nil, :class => "grey") %>
		<%=i.to_s%>
		<%end%>
	<%end%>
	</div>
	
	<div class="well well-sm">
	<h4>Considera ud que las horas sugeridas por el programa son sufucientes para asimilar adecuadamente sus contenidos?</h4>
	<%(1..5).each do |i|%>
		<%= label_tag(:intensidad,class: 'radio-inline') do%>
				<%= radio_button_tag(:intensidad,i.to_s ,nil, :class => "grey") %>
		<%=i.to_s%>
		<%end%>
	<%end%>
	</div>
	
	<div class="well well-sm">
	<h4>Los temas tratados en clase le han sido útiles por fuera de la misma?</h4>
	<%(1..5).each do |i|%>
		<%= label_tag(:utilidad,class: 'radio-inline') do%>
				<%= radio_button_tag(:utilidad,i.to_s ,nil, :class => "grey") %>
		<%=i.to_s%>
		<%end%>
	<%end%>
	</div>
</div>

<div class="modal-footer">
	<div class="actions">
		<button class="btn btn-green" type="submit">
			Enviar evaluación
		</button>
	</div>
</div>
</div>
<% end %>

app/views/courses/agregar_seccion.js.erb
$("#myModal").html("<%= escape_javascript(render(:partial => "form_agregar_seccion"))%>");
$('#myModal').modal('show');

app/views/courses/catalogo.html.erb
<%@materias.each do |m|%>
<div class="row">
	<div class="col-md-12">
		<div class="well well-sm">
			<div class="row">
				<div class="col-md-6">
					<h3><%=link_to m.nombre,course_path(m)%></h3>
					<p>
						<strong>Créditos: </strong><%= m.creditos%>
					</p>
				</div>
				<div class="col-md-6">
					<h4>Dificultad</h4>
					<div class="progress">
						<div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="<%= m.dificultad*100/5%>" aria-valuemin="0" aria-valuemax="100" style="width: <%= m.dificultad*100/5%>%">
							<%= m.dificultad%>
						</div>
					</div>
					<h4>Intensidad</h4>
					<div class="progress">
						<div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="<%= m.intensidad*100/5%>" aria-valuemin="0" aria-valuemax="100" style="width: <%= m.intensidad*100/5%>%">
							<%= m.intensidad%>
						</div>
					</div>
					<h4>Utilidad</h4>
					<div class="progress">
						<div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="<%= m.utilidad*100/5%>" aria-valuemin="0" aria-valuemax="100" style="width: <%=m.utilidad*100/5%>%">
							<%= m.utilidad%>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<%end%>

app/views/courses/cuestionario.js.erb
$("#myModal").html("<%= escape_javascript(render(:partial => "form_cuestionario"))%>");
$('#myModal').modal('show');

app/views/courses/edit.js.erb
$("#myModal").html("<%= escape_javascript(render(:partial => "form"))%>");
$('#myModal').modal('show');

app/views/courses/index.html.erb

<div class="row">
	<div class="col-md-12">
		<!-- start: BASIC TABLE PANEL -->
		<div class="panel panel-default">
			<div class="panel-heading">
				<i class="fa fa-external-link-square"></i>
				Materias
				<div class="panel-tools">
				</div>
			</div>
			<div class="panel-body">
				<table class="table table-hover" id="sample-table-1">
					<thead>
						<tr>
							<th class="center">#</th>
							<th>Nombre</th>
							<th class="left">Créditos</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<%@materias.each do |m|%>
						<tr>
							<td class="center"><%= m.id%></td>
							<td><%=link_to m.nombre,course_path(m)%></td>
							<td class="left"><%= m.creditos%></td>
							<td class="center">
							<div class="visible-md visible-lg hidden-sm hidden-xs">
								<%= link_to edit_course_path(m),:remote => true,class: "btn btn-xs btn-teal tooltips",:data=>{:placement=>"top","original-title"=>"Editar"} do%>
								<i class="fa fa-edit"></i>
								<%end%>
							
							<%= link_to course_path(m),class: "btn btn-xs btn-bricky tooltips",:data=>{:method=>"delete", :placement=>"top","original-title"=>"Eliminar"} do%>
								<i class="fa fa-times fa fa-white"></i>
							<%end%>	
							
							</div>
							<div class="visible-xs visible-sm hidden-md hidden-lg">
								<div class="btn-group">
									<a class="btn btn-primary dropdown-toggle btn-sm" data-toggle="dropdown" href="#"> <i class="fa fa-cog"></i> <span class="caret"></span> </a>
									<ul role="menu" class="dropdown-menu pull-right">
										<li role="presentation">
											<a role="menuitem" tabindex="-1" href="#"> <i class="fa fa-edit"></i> Edit </a>
										</li>
										<li role="presentation">
											<a role="menuitem" tabindex="-1" href="#"> <i class="fa fa-times"></i> Remove </a>
										</li>
									</ul>
								</div>
							</div></td>
						</tr>
						<%end%>
					</tbody>
				</table>
				<%= link_to 'Agregar materia',new_course_path, class: 'btn btn-blue btn-block',:remote => 'true'%>
			</div> 
		</div>
		<!-- end: BASIC TABLE PANEL -->

	</div>
</div>
<div class="modal fade" id="myModal" tabindex="-1" data-width="760" style="display: none;">
</div>


app/views/courses/mis_materias.html.erb
<div class="row">
	<div class="col-sm-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<i class="fa fa-reorder"></i>
				Mis materias
				<div class="panel-tools">
					<a class="btn btn-xs btn-link"><i class="fa fa-plus"></i></a>
				</div>
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-sm-12">
						<div class="tabbable">
							<ul id="tabs" class="nav nav-tabs tab-padding tab-space-3 tab-blue">
								<li class="active">
									<a href="#pendientes" data-toggle="tab"> Vistas </a>
								</li>
								
							</ul>
							<div class="tab-content">
								<div class="tab-pane in active" id="pendientes">
									<%@vistas.each do |v|%>
									<h4><%= v.nombre%></h4>
									<% @creditos_vistos += v.creditos%>
									<%end%>
								</div>
								
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<h3>Progreso</h3>
						<div class="progress">
							<div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="<%= (@creditos_vistos*100)/Course.sum(:creditos)%>" aria-valuemin="0" aria-valuemax="100" style="width: <%= (@creditos_vistos*100)/Course.sum(:creditos)%>%">
								<%= @creditos_vistos%>/<%= Course.sum(:creditos)%>
							</div>
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>

app/views/courses/new.js.erb
$("#myModal").html("<%= escape_javascript(render(:partial => "form"))%>");
$('#myModal').modal('show');

app/views/courses/show.html.erb
<div class="row">
	<div class="col-md-6">
		<h3>Descripción</h3>
		<p>
			<strong>Créditos: </strong><%= @materia.creditos%>
		</p>
		<p>
			<%= @materia.descripcion%>
		</p>
	</div>
	<div class="col-md-6">
		<h3>Censo estudiantil</h3>
		<h4>Dificultad</h4>
		<div class="progress">
			<div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="<%= @materia.dificultad*100/5%>" aria-valuemin="0" aria-valuemax="100" style="width: <%= @materia.dificultad*100/5%>%">
				<%= @materia.dificultad%>
			</div>
		</div>
		<h4>Intensidad</h4>
		<div class="progress">
			<div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="<%= @materia.intensidad*100/5%>" aria-valuemin="0" aria-valuemax="100" style="width: <%= @materia.intensidad*100/5%>%">
				<%= @materia.intensidad%>
			</div>
		</div>
		<h4>Utilidad</h4>
		<div class="progress">
			<div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="<%= @materia.utilidad*100/5%>" aria-valuemin="0" aria-valuemax="100" style="width: <%= @materia.utilidad*100/5%>%">
				<%= @materia.utilidad%>
			</div>
		</div>
	</div>
</div>
<%if current_user.has_role? :admin%>
<div class="row">
	<div class="col-md-12">
		<!-- start: BASIC TABLE PANEL -->
		<div class="panel panel-default">
			<div class="panel-heading">
				<i class="fa fa-external-link-square"></i>
				Secciones
			</div>
			<div class="panel-body">
				<table class="table table-hover" id="sample-table-1">
					<thead>
						<tr>
							<th class="center">#</th>
							<th>Semestre</th>
							<th class="hidden-xs">Estado</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<%@materia.sections.each do |s|%>
						<tr>
							<td class="center"><%= s.id%></td>
							<td class="hidden-xs"><%= s.semestre%></td>
							<td><%= s.estado%></td>
							<td class="center">
							<div class="visible-md visible-lg hidden-sm hidden-xs">
								<%= link_to section_path(s),class: "btn btn-xs btn-bricky tooltips",:data=>{:method=>"delete", :placement=>"top","original-title"=>"Eliminar"} do%>
								<i class="fa fa-times fa fa-white"></i>
								<%end%>
							</div>
							<div class="visible-md visible-lg hidden-sm hidden-xs">
								<a href="#" class="btn btn-xs btn-teal tooltips" data-placement="top" data-original-title="Edit"><i class="fa fa-edit"></i></a>
								<a href="#" class="btn btn-xs btn-green tooltips" data-placement="top" data-original-title="Share"><i class="fa fa-share"></i></a>
								<a href="#" class="btn btn-xs btn-bricky tooltips" data-placement="top" data-original-title="Remove"><i class="fa fa-times fa fa-white"></i></a>
							</div>
							<div class="visible-xs visible-sm hidden-md hidden-lg">
								<div class="btn-group">
									<a class="btn btn-primary dropdown-toggle btn-sm" data-toggle="dropdown" href="#"> <i class="fa fa-cog"></i> <span class="caret"></span> </a>
									<ul role="menu" class="dropdown-menu pull-right">
										<li role="presentation">
											<%= link_to edit_section_path(s),:remote => true,class: "btn btn-xs btn-teal tooltips",:data=>{:placement=>"top",:originaltitle=>"Edit"} do%>
											<i class="fa fa-edit"></i>
											<%end%>
											<a role="menuitem" tabindex="-1" href="#"> <i class="fa fa-edit"></i> Edit </a>
										</li>
									</ul>
								</div>
							</div></td>
						</tr>
						<%end%>
					</tbody>
				</table>
				<%= link_to 'Agregar nueva sección de materia',@materia.id.to_s+'/agregar_seccion', class: 'btn btn-blue btn-block',:remote => 'true'%>
			</div>
		</div>
		<!-- end: BASIC TABLE PANEL -->
	</div>
</div>
<%end%>
<%if current_user.has_role? :estudiante and !@materia.users.exists? current_user.id%>
<div class="row">
	<div class="col-md-12">
		<%= link_to 'Evaluar materia y marcar como vista',@materia.id.to_s+'/cuestionario', class: 'btn btn-blue btn-block',:remote => 'true'%>
	</div>
</div>
<%end%>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<i class="fa fa-external-link-square"></i>
				Comentarios
			</div>
			<div class="panel-body">
			
			<%= form_tag(@materia.id.to_s+"/guardar_comentario",:method=>"get") do%>
				<%=text_area_tag 'comment'%>
				<%=submit_tag%>
			<%end%>
			
			<%@materia.comments.each do|c|%>
				<div class="well">
					<strong><%=c.user.email%></strong>
					<p><%=c.comentario%></p>
				</div>
			<%end%>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="myModal" tabindex="-1" data-width="760" style="display: none;"></div>