config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users, controllers: { :sessions => "users/sessions", :registrations => 'users/registrations', 
    :confirmations => 'users/confirmations', :passwords => "users/passwords" }
 
  resources :users
  resources :appointments
  get "/courses/catalogo"=> "courses#catalogo"
  get "/courses/mis_materias"=> "courses#mis_materias"
  resources :courses
  get "/courses/:id/cuestionario/"=>"courses#cuestionario"
  get "/courses/:id/guardar_resultados"=>"courses#guardar_resultados"
  get "/courses/:id/guardar_comentario"=>"courses#guardar_comentario"
  
  resources :sections
  get "/courses/:id/agregar_seccion/"=>"courses#agregar_seccion"
  get "/appointments/:id/confirmar_cita/"=> "appointments#confirmar_cita"
  post "/appointments/generar_reporte/"=> "appointments#generar_reporte"
  resources :schedules
  get 'administracion/index'
  get "consejeria/index"
  root :to => "consejeria#index"
  get "consejeria/" => "consejeria#index"
  
  
  

end

app/models/appointment.rb
# == Schema Information
#
# Table name: appointments
#
#  id           :integer          not null, primary key
#  consejero_id :integer
#  alumno_id    :integer
#  fecha        :datetime
#  estado       :string(255)
#  reporte      :text(65535)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null


# Clase que representa un objeto de tipo Appointment 

class Appointment < ActiveRecord::Base
  resourcify
  belongs_to :consejero, :class_name => 'User', :foreign_key => 'consejero_id'
  belongs_to :alumno, :class_name => 'User', :foreign_key => 'alumno_id'
  require 'tod'
  
  # Método que calcula la próxima fecha del calendario de acuerdo a una hora y un día de la semana
  # * *Parámetros*    :
  #   - +hora+ -> hora de de la disponibilidad
  #   - +dia_semana+ -> Día de la semana de la disponibilidad
  # * *Returns* :
  #   - La fecha de acuerdo al día de la semana y hora como un objeto de tipo Datetime
  def disponibilidad(hora, dia_semana)
    puts "en Dispinibilidad"
    man= Time.now
    man= man +1.day
    while man.wday != dia_semana
      puts "dia semana"
      puts man.wday
      puts dia_semana
      man = man +1.day
    end
    hora = hora.to_time_of_day
    hora= hora.on man
    hora = DateTime.parse(hora.to_s)
    return hora
  end
  
end

app/controllers/appointments_controller.rb
# Clase encargada de controlar las acciones concernientes a los objetos de tipo Appointment
class AppointmentsController < ApplicationController

  # Parámetros permitidos para aleterar provenientes de la vista
  def appointment_params
      params.require(:appointment).permit(:id,:alumno_id,:fecha ,:consejero_id,:estado,:reporte)
    end
  
  #CU17-R02,CU17-R03
  # Muestra un listado de los objetos de tipo Appointment asociados al usuario. Estos objetos dependen del rol de usuario si es de tipo consejero o estudiante
  def index
    if current_user.has_role? :estudiante
      @citas = Appointment.where :alumno_id =>current_user.id
    end
    if current_user.has_role? :consejero
      @citas = Appointment.where :consejero_id =>current_user.id
    end
  end
  
  # Retorna el registro de tipo Appointment solicitado por el usuario
  def show
    @cita = Appointment.find(params[:id])
  end
  
  # CU0013-R1 CU0015-R1 CU016-R1
  # Prepara la información requerida para la solicitud de un cita
  def new
    @dia_semana= Hash.new
    @dia_semana['Lunes']=1
    @dia_semana['Martes']=2
    @dia_semana['Miercoles']=3
    @dia_semana['Jueves']=4
    @dia_semana['Viernes']=5
    @appointment=Appointment.new
    @horarios= Array.new
    Schedule.all.each do |sc|
      cita = Appointment.new
      cita.fecha = cita.disponibilidad(sc.hora_inicio,@dia_semana[sc.dia_semana])
      cita.consejero_id=sc.user_id
      cita.alumno_id= current_user.id
      cita.estado = "PENDIENTE"
      @horarios<<cita
    end
  end

  # Prepara la información del registro buscado para su edición
  # * *Parámetros*    :
  #   - +id+ -> identificador único del objeto de tipo Appointment
  # * *Resultado*     :
  #   - se asigna a la variable @cita el objeto de tipo Appointment encontrado en la base de datos
  def edit
    @cita = Appointment.find(params[:id])
  end
  
  # CU0014-R1,CU17-R04
  # Cambia el estado de una cita de "PENDIENTE" a "COFIRMADA"
  # * *Parámetros*    :
  #   - +id+ -> identificador único del consejero
  # * *Resultado* :
  #   - Se cambia el atributo Estado del objeto Appointment y se guarda en la base de datos 
  def confirmar_cita
    @cita = Appointment.find(params[:id])
    @cita.estado="CONFIRMADA"
    if @cita.save
      redirect_to :appointments, :flash => { :success => 'Su cita ha sido confirmada satisfactoriamente' }
    else
      render :action =>'index'
    end
  end
  
  # CU0013-R1
  # Guarda el reporte de la cita generado por el consejero
  # * *Parámetros*    :
  #   - +id+ -> identificador único del objeto de tipo Appointment
  #   - +reporte+ -> Text representando el acta de la cita
  # * *Resultado* :
  #   - Se inserta el reporte en el registro de la cita en la base de datos y se modifica el estado de la cita a CONCLUIDA
  def generar_reporte
    @cita = Appointment.find(params[:appointment][:id])
    @cita.reporte= params[:appointment][:reporte]
    @cita.estado="CONCLUIDA"
    if @cita.save
      redirect_to :appointments, :flash => { :success => 'Su cita ha concluido satisfactoriamente' }
    else
      render :action =>'index'
    end
  end
  
  # CU0013-R1
  # Guarda los datos de la cita en la base de datos
  # * *Parámetros*    :
  #   - +consejeror_id+ -> identificador único del consejero
  #   - +alumno_id+ -> identificador único del alumno
  #   - +fecha+ -> Fecha de tipo DateTime de la cita
  # * *Resultado* :
  #   - El objeto de tipo de Appointment se guarda exitosamente en la base de datos
  def create
    puts "---- parametros de creacion----"
    puts params
    @appointment = Appointment.new(appointment_params)

    if @appointment.save
      redirect_to :appointments, :flash => { :success => 'Su cita ha sido creada satisfactoriamente' }
    else
      render :action => 'index'
    end
  end

  # CU0014-R1 CU0014-R2
  # Actualiza los datos de un objeto de tipo Appointment
  # * *Parámetros*    :
  #   - +id+ -> Identificador único del registro de tipo Appointment a modificar
  #   - +fecha+ -> Nueva fecha de tipo DateTime 
  # * *Resultado* :
  #   - Los cambios en el registro se guardan exitosamente en la base de datos
  def update
    @cita = Appointment.find(params[:id])
   
    if @cita.update_attributes(user_params)
      sign_in(@user, :bypass => true) if @user == current_user
      redirect_to :appointments, :flash => { :success => 'Datos de cita actualizados satisfactoriamente.' }
    else
      puts "Parametros"
      redirect_to :appointments, :flash => { :error => 'No ha sido posible actualizar los datos de Cita.' }
    end
  end

  # CU0014-R2,CU017-R05
  #Elimina un registro de tipo Appointment de la base de datos
  # * *Parámetros*    :
  #   - +id+ -> Identificador único del registro de tipo Appointment a eliminar
  # * *Resultado* :
  #   - El registro representado por el objeto Appointment se elimina exitosamente de la base de datos
  def destroy
    @cita = Appointment.find(params[:id])
    @cita.destroy
    redirect_to appointments_path, :flash => { :success => 'Cita eliminada del sistema.' }
  end
end

app/helpers/appointments_helper.rb
# Módulo de métodos de ayuda específicos para las vistas concernientes a Appointment. Es un clase vacía pues no ha habido necesidad hasta el momento ningun método
module AppointmentsHelper
end

app/views/appointments/_citas.html.erb

<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal">
		&times;
	</button>
	<h3>Horarios disponibles</h3>
</div>
<div class="modal-body">
<%@horarios.each do |h|%>
	<%@appointment=h%>
	<%= form_for @appointment, url: appointments_path, html:{class:'form-horizontal',:method =>:post} do |f| %>
		<%= f.hidden_field(:fecha,:value =>@appointment.fecha) %>
		<%= f.hidden_field(:alumno_id,:value => @appointment.alumno_id) %>
		<%= f.hidden_field(:consejero_id,:value => @appointment.consejero_id) %>
		<%= f.hidden_field(:estado,:value => @appointment.estado) %>
		<%= f.hidden_field(:reporte,:value => @appointment.reporte) %>
	<div class="well well-sm">
	<h3><%=@appointment.consejero.email%></h3>
	<h3><%=@appointment.fecha.strftime("%A %B %d %I:%M %p")%></h3>
		<div class="actions">
			<button class="btn btn-green" type="submit">
				Reservar
			</button>
		</div>
	</div>
		<%end%>
<%end%>	
<div class="modal-footer">
	
</div>

app/views/appointments/_detalle.html.erb
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal">
		&times;
	</button>
	<h3>Reporte</h3>
</div>
<div class="modal-body">
<p><%=@cita.reporte%></p>
</div>
<div class="modal-footer">
	
</div>

app/views/appointments/_reporte.html.erb
<%= form_for @cita, url: appointments_generar_reporte_path, html:{class:'form-horizontal',:method =>:post} do |f| %>
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal">
		&times;
	</button>
	<h3>Generar Reporte</h3>
</div>
<div class="modal-body">
	<%= f.hidden_field(:id,:value =>@cita.id) %>
	<%= f.text_area(:reporte)%>
</div>
<div class="modal-footer">
	<div class="actions">
		<button class="btn btn-green" type="submit">
			Guardar
		</button>
	</div>
</div>
<%end%>


app/views/appointments/edit.html.erb
<h1>Edit User</h1>

<%= render 'reporte' %>

app/views/appointments/edit.js.erb
$("#reportes").html("<%= escape_javascript(render(:partial => "reporte"))%>");
$("#reportes").modal('show');

app/views/appointments/index.html.erb
<div class="row">
	<div class="col-sm-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<i class="fa fa-reorder"></i>
				Estado de citas
				<div class="panel-tools">
					<a class="btn btn-xs btn-link"><i class="fa fa-plus"></i></a>
				</div>
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-sm-12">
						<div class="tabbable">
							<ul id="tabs" class="nav nav-tabs tab-padding tab-space-3 tab-blue">
								<li class="active">
									<a href="#pendientes" data-toggle="tab"> Pendientes </a>
								</li>
								<li>
									<a href="#confirmadas" data-toggle="tab"> Confirmadas </a>
								</li>
								<li>
									<a href="#concluidas" data-toggle="tab"> Concluidas </a>
								</li>
							</ul>
							<div class="tab-content">
								<div class="tab-pane in active" id="pendientes">
									<table class="table table-hover" id="sample-table-1">
										<thead>
											<tr>
												<th class="left">Consejero</th>
												<th class="left">Alumno</th>
												<th class="left">Dia</th>
												<th></th>
											</tr>
										</thead>
										<tbody>
											<%@citas.each do |cita|%>
											<%if cita.estado=='PENDIENTE'%>
											<tr>
												<td class="left"><%= cita.consejero.email%></td>
												<td class="left"><%= cita.alumno.email%></td>
												<td class="left"><%= cita.fecha.strftime("%A %B %d %I:%M %p")%></td>
												<td>
												<div class="visible-md visible-lg hidden-sm hidden-xs">
													<%= link_to appointment_path(cita),class: "btn btn-xs btn-bricky tooltips",:data=>{:method=>"delete", :placement=>"top","original-title"=>"Eliminar"} do%>
													<i class="fa fa-times fa fa-white"></i>
													<%end%>
													<%if current_user.has_role? :consejero%>
													<%= link_to "/appointments/"+cita.id.to_s+"/confirmar_cita",class: "btn btn-xs btn-teal tooltips",:data=>{:method=>"get", :placement=>"top","original-title"=>"confirmar"} do%>
													<i class="fa fa-check fa fa-white"></i>
													<%end%>
													<%end%>
						
												</div>
												<div class="visible-xs visible-sm hidden-md hidden-lg">
													<div class="btn-group">
														<a class="btn btn-primary dropdown-toggle btn-sm" data-toggle="dropdown" href="#"> <i class="fa fa-cog"></i> <span class="caret"></span> </a>
														<ul role="menu" class="dropdown-menu pull-right">
															<li role="presentation">
																<%= link_to appointment_path(cita),role: "menuitem",tabindex: "-1",:data=>{:method=>"delete", :placement=>"top","original-title"=>"Eliminar"} do%>
																<i class="fa fa-check"></i> Eliminar
																<%end%>
															</li>
														</ul>
													</div>
												</div>
												<div class="visible-xs visible-sm hidden-md hidden-lg">
													<div class="btn-group">
														<a class="btn btn-primary dropdown-toggle btn-sm" data-toggle="dropdown" href="#"> <i class="fa fa-cog"></i> <span class="caret"></span> </a>
														<ul role="menu" class="dropdown-menu pull-right">
															<%if current_user.has_role? :consejero%>
															<li role="presentation">
																<%= link_to "confirmar","/appointments/"+cita.id.to_s+"/confirmar_cita" ,role: "menuitem",tabindex: "-1",:data=>{ :method=>"get" ,:placement=>"top","original-title"=>"Eliminar"} %>
															</li>
															<%end%>
														</ul>
													</div>
												</div> <%end%> </td>
											</tr>
											<%end%>
											
										</tbody>
									</table>
									<p>
										Aqui van las citas pedidas que no han sido confirmadas
									</p>
								</div>
								<div class="tab-pane" id="confirmadas">
									<table class="table table-hover" id="sample-table-1">
										<thead>
											<tr>
												<th class="left">Consejero</th>
												<th class="left">Alumno</th>
												<th class="left">Dia</th>
												<th></th>
											</tr>
										</thead>
										<tbody>
											<%@citas.each do |cita|%>
											<%if cita.estado=='CONFIRMADA'%>
											<tr>
												<td class="left"><%= cita.consejero.email%></td>
												<td class="left"><%= cita.alumno.email%></td>
												<td class="left"><%= cita.fecha.strftime("%A %B %d %I:%M %p")%></td>
												<td>
												<%if current_user.has_role? :consejero%>
												<div class="visible-md visible-lg hidden-sm hidden-xs">
													<%= link_to edit_appointment_path(cita),:remote => true,class: "btn btn-xs btn-teal tooltips",:data=>{ :placement=>"top","original-title"=>"Edit"} do%>
													<i class="fa fa-check fa fa-white"></i>
													<%end%>
												</div>
												<div class="visible-xs visible-sm hidden-md hidden-lg">
													<div class="btn-group">
														<a class="btn btn-primary dropdown-toggle btn-sm" data-toggle="dropdown" href="#"> <i class="fa fa-cog"></i> <span class="caret"></span> </a>
														<ul role="menu" class="dropdown-menu pull-right">
															<li role="presentation">
																<%= link_to "confirmar",edit_appointment_path(cita),:remote =>true ,role: "menuitem",tabindex: "-1",:data=>{ :method=>"get" ,:placement=>"top","original-title"=>"Eliminar"} %>
															</li>
														</ul>
													</div>
												</div>
												<%end%> 
												<%end%> </td>
											</tr>
											<%end%>
											
										</tbody>
									</table>
									<p>
										Aqui van las citas que han sido confirmadas
									</p>
								</div>
								<div class="tab-pane" id="concluidas">
								<table class="table table-hover" id="sample-table-1">
										<thead>
											<tr>
												<th class="left">Consejero</th>
												<th class="left">Alumno</th>
												<th class="left">Dia</th>
												<th></th>
											</tr>
										</thead>
										<tbody>
											<%@citas.each do |cita|%>
											<%if cita.estado=='CONCLUIDA'%>
											<tr>
												<td class="left"><%= cita.consejero.email%></td>
												<td class="left"><%= cita.alumno.email%></td>
												<td class="left"><%= cita.fecha.strftime("%A %B %d %I:%M %p")%></td>
												<td>
												<div class="visible-md visible-lg hidden-sm hidden-xs">
									
													
													<%= link_to "/appointments/"+cita.id.to_s,:remote=>true,class: "btn btn-xs btn-teal tooltips",:data=>{:method=>"get", :placement=>"top","original-title"=>"detalles"} do%>
													<i class="clip-eye"></i>
													<%end%>
													
						
												</div>
												<div class="visible-xs visible-sm hidden-md hidden-lg">
													<div class="btn-group">
														<a class="btn btn-primary dropdown-toggle btn-sm" data-toggle="dropdown" href="#"> <i class="fa fa-cog"></i> <span class="caret"></span> </a>
														<ul role="menu" class="dropdown-menu pull-right">
															<li role="presentation">
																<%= link_to appointment_path(cita),role: "menuitem",tabindex: "-1",:data=>{:method=>"delete", :placement=>"top","original-title"=>"Eliminar"} do%>
																<i class="clip-eye"></i> Eliminar
																<%end%>
															</li>
														</ul>
													</div>
												</div>
												<div class="visible-xs visible-sm hidden-md hidden-lg">
													<div class="btn-group">
														<a class="btn btn-primary dropdown-toggle btn-sm" data-toggle="dropdown" href="#"> <i class="fa fa-cog"></i> <span class="caret"></span> </a>
														<ul role="menu" class="dropdown-menu pull-right">
															<%if current_user.has_role? :consejero%>
															<li role="presentation">
																<%= link_to "confirmar","/appointments/"+cita.id.to_s+"/confirmar_cita" ,role: "menuitem",tabindex: "-1",:data=>{ :method=>"get" ,:placement=>"top","original-title"=>"Eliminar"} %>
															</li>
															<%end%>
														</ul>
													</div>
												</div> <%end%> </td>
											</tr>
											<%end%>
											
										</tbody>
									</table>
									<p>
										Citas concluidas
									</p>
								</div>
							</div>
						</div>
					</div>

				</div>
				<%if current_user.has_role? :estudiante%>
				<%= link_to 'Pedir cita con un consejero',new_appointment_path, class: 'btn btn-blue btn-block',:remote => 'true'%>
				<%end%>
			</div>
		</div>
	</div>
	<div class="modal fade" id="citas_disponibles" tabindex="-1" data-width="760" style="display: none;"></div>
	<div class="modal fade" id="reportes" tabindex="-1" data-width="760" style="display: none;"></div>

app/views/appointments/new.js.erb
$("#citas_disponibles").html("<%= escape_javascript(render(:partial => "citas"))%>");
$('#citas_disponibles').modal('show');

app/views/appointments/show.js.erb
$("#reportes").html("<%= escape_javascript(render(:partial => "detalle"))%>");
$("#reportes").modal('show');